# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusStoryManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CampusStoryManager
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
  ]
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Pods for CampusStory
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'SDWebImage/WebP'
  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer/ios'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

end
